# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

server:
  port: 9997
topic:
  topics:
    toRequestsParser: toRequestsParser
    toDownloader: toDownloader
    toMetadataParser: toMetadataParser
kafka:
  clusterType: distributed
  producer:
    serializer.class: kafka.serializer.StringEncoder
    key.serializer.class: kafka.serializer.StringEncoder
    metadata.broker.list: ${kafka.uri}
    retry.backoff.ms: 500

  consumer:  
    group.id: default_group
    auto.commit.interval.ms: 1000
    auto.offset.reset: smallest 
    #watch for chroot (kafka)
    #TODO: add /kafka path on shifting from mock to a real CDH
    zookeeper.connect: "${zookeeper.uri}"
    zookeeper.chroot: kafka
    zookeeper.session.timeout.ms: 400
    zookeeper.sync.time.ms: 200

services:
  downloader: "${downloader.uri:http://localhost:8090}"
  metadataparser: "${metadata.parser.uri:http://localhost:8900}"
  user-management: "${user.management.uri:http://localhost:9998}"
  
spring.profiles.active: inmemory,local

callback:
  url: "${data.acquisition.uri:http://localhost:8080}/rest/das/callbacks/{app}/{requestId}"

security:
  ignored: /open,/v2/api-docs,/api-docs/default/*,/images/*,/lib/*,/css/*,/health,/info

spring.oauth2.resource:
  id: tap
  jwt:
    keyUri: ${sso.tokenKey}

logging.level:
  root: INFO 
#  org.springframework: INFO
#  org.trustedanalytics: INFO
#  kafka: INFO

cf:
  resource: ${sso.apiEndpoint}
  uaa: ${sso.uaaUri}

endpoints.enabled: false
endpoints.health.enabled: true
endpoints.info.enabled: true
endpoints.info.sensitive: false

# http://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-application-info-git
management:
  info:
    git:
      mode: full

# http://docs.spring.io/spring-boot/docs/current/reference/html/howto-build.html#howto-build-info
info:
  name: "@project.artifactId@"
  app_version: "@project.version@"
  build:
    group: "@project.groupId@"
    artifact: "@project.artifactId@"
    version: "@project.version@"
    name: "@project.name@"
    time: "@build.time@"
